config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboards#show'
  end

  root to: 'homes#show'

  resources :shouts, only: %i[create show]

  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, only: [:create]

  resources :users, only: %i[create show] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
# frozen_string_literal: true

class Guest
  def email
    ''
  end
end

app/models/shout.rb
# frozen_string_literal: true

class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true

  validates :user, presence: true

  default_scope { order(created_at: :desc) }

  delegate :username, to: :user
end

app/models/text_shout.rb
# frozen_string_literal: true

class TextShout < ApplicationRecord
  validates :body, presence: true, length: { in: 1..144 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true

  has_many :shouts, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.shouts
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  before_action :redirect_to_dashboard_if_signed_in

  def show
    render
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Clearance::SessionsController
  private

  def authenticate(_)
    super(session_params)
  end

  def session_params
    { session: session_params_with_email }
  end

  def session_params_with_email
    params
      .require(:session)
      .permit(:password)
      .merge(email: user.email)
  end

  def user
    User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
  end

  def email_or_username
    params[:session][:email_or_username]
  end
end

app/controllers/shouts_controller.rb
# frozen_string_literal: true

class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end

  def create
    shout = current_user.shouts.create(shout_params)
    redirect_to root_path, redirect_options_for(shout)
  end

  private

  def shout_params
    { content: content_from_params }
  end

  def content_from_params
    TextShout.new(content_params)
  end

  def content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: 'Shouted successfully!' }
    else
      { alert: 'Could not shout :(' }
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < Clearance::UsersController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then 'alert alert-success'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/dashboards/show.haml
%h1.text-light Dashboard
.row.pt-4
  .col
    .card
      .card-body
        = form_for @shout do |form|
          = form.fields_for :content do |content_form|
            .form-group
              = label_tag 'body', 'New shout:', class: "card-title font-weight-bold"
              = content_form.text_field :body, placeholder: "Enter your shout...", required: true, class: "form-control"
            = form.submit "shout!", class: "btn btn-primary"
  .col.bg-light.p-4
    = render @shouts

app/views/homes/show.haml
%h1 Hello!!

app/views/layouts/_flash.haml
#flash
  - flash.each do |key, value|
    %div{:class => "#{flash_class(key)} mb-0 rounded-0"}= value

app/views/layouts/_nav.haml
%nav.navbar.navbar-dark.bg-primary.text-white

  - if signed_in?
    .navbar-brand.mr-auto
      Shoutr
    .navbar-text.mr-4
      #{current_user.email}
    .nav-item
      #{link_to 'Sign out', sign_out_path, method: :delete, class: "btn btn-outline-light"}
  - else
    = link_to 'Sign in', sign_in_path, class: "btn btn-outline-light"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shoutr
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  %body.bg-dark
    = render partial: "/layouts/nav"
    = render partial: "/layouts/flash"

    .container.pt-4
      = yield

app/views/shouts/_shout.haml
.card.mb-4.shadow-sm
  .card-body
    = link_to shout.username, shout.user, class: "card-title font-weight-bold"
    %p.mb-0
      = shout.content.body
  .card-footer.text-right
    = link_to shout, class: "card-link" do
      = "Shouted #{time_ago_in_words(shout.created_at)} ago"

app/views/shouts/show.haml
%h1.text-center.text-light
  Shout
.row.justify-content-center.mt-4
  .col-md-4
    = render @shout

app/views/users/_form.html.haml
.text-field
  = form.label :email
  = form.email_field :email
.text-field
  = form.label :username
  = form.text_field :username
.password-field
  = form.label :password
  = form.password_field :password

app/views/users/new.html.haml
#clearance.sign-up
  %h2= t(".title")
  = form_for @user do |form|
    = render partial: '/users/form', object: form
    .submit-field
      = form.submit
    .other-links
      = link_to t(".sign_in"), sign_in_path

app/views/users/show.haml
%h1.text-center.text-light
  = @user.username
.row.justify-content-center.mt-4
  .col-md-4
    = render @shouts